### ISSUE TITLE
WiFi switch crash

### ISSUE THREAD

**Issue by tombartindale** [our-story-media/ourstory-android#2]
If the app is open, connected to a wifi and then i switch to the our story wifi in the settings, then the app crashes.

**Comment by delvinv** [comment]
Also is it possible to Check SSID of connected network to make sure it is connected to OurStory (obvs probably not ideal to hardcode SSIDs into apps but maybe if we set the SSID in the settings panel of the backend, then this can be relayed to the app on first login) and thus each time participant tries to do something that involves wifi and the phone is not connected to wifi with correct ssid then we can give a meaningful error! (and we can do other cool things like showing the shoot administrator how many and which tablets are connected to the backend, thus they can identify if any tablets are offline and they shouldnt be). 

Obvs ignore if the above is an unnecessary extra!
