### ISSUE TITLE
Video upload not completing..

### ISSUE THREAD

**Issue by tombartindale** [our-story-media/ourstory-android#3]
Error: (after resetting) - object reference error..
Dont remember how to exactly replicate this, i’ll have a go tomorrow on the titan, but basically it was about captured videos not uploading even though i tried refreshing..

**Comment by delvinv** [comment]
Additionally, uploading videos results in user being logged out and needing to log back in (by clearing all recent apps, joining shoot, capture video and then being taken inside the app to the Capture tab)
